### ISSUE TITLE
Graph.ical offline

### ISSUE THREAD

**Issue by MarioPeper** [kchapelier/procjam2018#3]
I really like Graph.ical and would also like to use it offline. So I downloaded it from github but how do I start it?

**Comment by kchapelier** [comment]
Hi,

If you want to run it locally, you'll need to build/"compile" it and have a local webserver.

To build it, you'll need to have node.js and npm installed on your computer (not sure if the latest version will be compatible to be honest), then go to the root folder where the file "package.json" is located, the run the following commands :

```
npm i
npm run build-styles
npm run build-scripts
```

Alternatively, you can download the compiled files directly from the online site and place them in "public/"
https://www.kchapelier.com/graph.ical/main.js
https://www.kchapelier.com/graph.ical/main.css

Then setup a webserver to serves the file located in "public/". It's only a bunch of static files (html, js, css and woff2 fonts) so any webserver should do (MAMP, WAMP, `python -m SimpleHTTPServer 8000`, `php -S localhost:8000`, `npx http-server -p 8000`, etc.).

**Comment by MarioPeper** [comment]
Thanks a lot, it works for me even without a server. But not with Dark Reader. So I have to have a look at main.css. :-)

**Comment by kchapelier** [comment]
Nice! If you got the build system working, ~all~ _most of what_ you look for should be in this file :
https://github.com/kchapelier/procjam2018/blob/master/src/stylus/variables.styl

**Comment by MarioPeper** [comment]
Thanks again. I will take a closer look at this. But this way I can work with it offline. ;-)
